//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juegos.Serios.Bathroom.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juegos.Serios.Bathroom.Domain.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de entrada no válidos.
        /// </summary>
        public static string Api_Badrequest {
            get {
                return ResourceManager.GetString("Api_Badrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formulario se registro exitosamente..
        /// </summary>
        public static string Api_Get_RegisterQuestionnaireAnswer_Created_Response {
            get {
                return ResourceManager.GetString("Api_Get_RegisterQuestionnaireAnswer_Created_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso aun no fue tomado el dia de hoy..
        /// </summary>
        public static string Api_Get_Weight_ValidatedWeight_Response_failed {
            get {
                return ResourceManager.GetString("Api_Get_Weight_ValidatedWeight_Response_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso ya fue tomado el dia de hoy..
        /// </summary>
        public static string Api_Get_Weight_ValidatedWeight_Response_success {
            get {
                return ResourceManager.GetString("Api_Get_Weight_ValidatedWeight_Response_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una respuesta para el cuestionario asociada con el ID de peso proporcionado..
        /// </summary>
        public static string Api_Questionnaire_AnswerAlreadyExists {
            get {
                return ResourceManager.GetString("Api_Questionnaire_AnswerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los datos del cuestionario son inválidos o están incompletos..
        /// </summary>
        public static string Api_Questionnaire_InvalidData {
            get {
                return ResourceManager.GetString("Api_Questionnaire_InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más identificadores de preguntas proporcionados no son válidos o no corresponden al cuestionario..
        /// </summary>
        public static string Api_Questionnaire_InvalidQuestionIDs {
            get {
                return ResourceManager.GetString("Api_Questionnaire_InvalidQuestionIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador del cuestionario proporcionado no es válido o no existe..
        /// </summary>
        public static string Api_Questionnaire_InvalidQuestionnaireID {
            get {
                return ResourceManager.GetString("Api_Questionnaire_InvalidQuestionnaireID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de preguntas proporcionadas no coincide con la cantidad esperada en el cuestionario..
        /// </summary>
        public static string Api_Questionnaire_MismatchQuestionCount {
            get {
                return ResourceManager.GetString("Api_Questionnaire_MismatchQuestionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los identificadores de preguntas tiene uno o mas duplicado..
        /// </summary>
        public static string Api_Questionnaire_MismatchQuestionCountDuplicated {
            get {
                return ResourceManager.GetString("Api_Questionnaire_MismatchQuestionCountDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ocurrio un error, comuniquese con el administrador..
        /// </summary>
        public static string Api_Servererror {
            get {
                return ResourceManager.GetString("Api_Servererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La fecha de creación del usuario no debe estar vacía..
        /// </summary>
        public static string Api_Weight_InvalidCreatedUser {
            get {
                return ResourceManager.GetString("Api_Weight_InvalidCreatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no debe estar vacio..
        /// </summary>
        public static string Api_Weight_InvalidUserId {
            get {
                return ResourceManager.GetString("Api_Weight_InvalidUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso registrado no debe estar vacío..
        /// </summary>
        public static string Api_Weight_InvalidWeight {
            get {
                return ResourceManager.GetString("Api_Weight_InvalidWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El identificador del peso no existe..
        /// </summary>
        public static string Api_Weight_InvalidWeight_NotFound {
            get {
                return ResourceManager.GetString("Api_Weight_InvalidWeight_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron pesos, comuniquese con el administrador..
        /// </summary>
        public static string Api_Weight_NoPreviousRecords {
            get {
                return ResourceManager.GetString("Api_Weight_NoPreviousRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso se mantiene..
        /// </summary>
        public static string Domain_Weight_IsEqual {
            get {
                return ResourceManager.GetString("Domain_Weight_IsEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso aumento 1 kilo..
        /// </summary>
        public static string Domain_Weight_IsSuperiorByOne {
            get {
                return ResourceManager.GetString("Domain_Weight_IsSuperiorByOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso es igual o superior a 2 kilo..
        /// </summary>
        public static string Domain_Weight_IsSuperiorByTwo {
            get {
                return ResourceManager.GetString("Domain_Weight_IsSuperiorByTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El peso ya fue tomado el dia de hoy..
        /// </summary>
        public static string Domain_Weight_IsTakeToday {
            get {
                return ResourceManager.GetString("Domain_Weight_IsTakeToday", resourceCulture);
            }
        }
    }
}
