//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juegos.Serios.Bathroom.Application.Resources.BathroomHtml {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppBathroomMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppBathroomMessages() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juegos.Serios.Bathroom.Application.Resources.BathroomHtml.AppBathroomMessages", typeof(AppBathroomMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Aviso Importante sobre tu Salud&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;font-family: Arial, sans-serif;&quot;&gt;
        ///
        ///        &lt;h2&gt;Aviso Importante sobre tu Salud&lt;/h2&gt;
        ///
        ///        &lt;p&gt;Hola {name} {lastName},&lt;/p&gt;
        ///
        ///        &lt;p&gt;Hemos notado un incremento en tu peso de 1 kilo. Si bien esto puede ser una fluctuación normal, queremos que estés atento a cualquier otro [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Emails_SuperiorByOne_Body {
            get {
                return ResourceManager.GetString("Emails_SuperiorByOne_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta de Salud: Observa estos síntomas importantes.
        /// </summary>
        internal static string Emails_SuperiorByOne_Subject {
            get {
                return ResourceManager.GetString("Emails_SuperiorByOne_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Alerta de Salud Urgente&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;font-family: Arial, sans-serif;&quot;&gt;
        ///
        ///        &lt;h2&gt;Alerta de Salud Urgente&lt;/h2&gt;
        ///
        ///        &lt;p&gt;Hola {name} {lastName},&lt;/p&gt;
        ///
        ///        &lt;p&gt;Hemos notado un incremento significativo en tu peso de más de 2 kilos. Este cambio puede estar relacionado con una descompensación severa, por lo que es c [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Emails_SuperiorByTwo_Body {
            get {
                return ResourceManager.GetString("Emails_SuperiorByTwo_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alerta Urgente de Salud: Acción Inmediata Necesaria.
        /// </summary>
        internal static string Emails_SuperiorByTwo_Subject {
            get {
                return ResourceManager.GetString("Emails_SuperiorByTwo_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;es&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;Felicidades por tu progreso&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div style=&quot;font-family: Arial, sans-serif;&quot;&gt;
        ///
        ///        &lt;h2&gt;Felicidades por tu progreso&lt;/h2&gt;
        ///
        ///        &lt;p&gt;Hola {name} {lastName},&lt;/p&gt;
        ///
        ///        &lt;p&gt;Felicidades, vamos bien hasta ahora. Todo está bajo control, continua con tu autocuidado.&lt;/p&gt;
        ///
        ///        &lt;p&gt;Esperamos que sigas comprometido con t [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Emails_WeightEqual_Body {
            get {
                return ResourceManager.GetString("Emails_WeightEqual_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continúa así: todo está bajo control.
        /// </summary>
        internal static string Emails_WeightEqual_Subject {
            get {
                return ResourceManager.GetString("Emails_WeightEqual_Subject", resourceCulture);
            }
        }
    }
}
