//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Juegos.Serios.Authenticacions.Domain.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppMessages
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Juegos.Serios.Authenticacions.Domain.Resources.AppMessages", typeof(AppMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string Api_Get_User_UpdatedPassword_Response
        {
            get
            {
                return ResourceManager.GetString("Api_Get_User_UpdatedPassword_Response", resourceCulture);
            }
        }
        public static string Domain_User_Password_Empty
        {
            get
            {
                return ResourceManager.GetString("Domain_User_Password_Empty", resourceCulture);
            }
        }
        public static string Api_TokenApplication_Invalid
        {
            get
            {
                return ResourceManager.GetString("Api_TokenApplication_Invalid", resourceCulture);
            }
        }
        public static string Api_Created_User_IsConsentendIsfalse_Response
        {
            get
            {
                return ResourceManager.GetString("Api_Created_User_IsConsentendIsfalse_Response", resourceCulture);
            }
        }
        public static string Api_Get_Rol_Response
        {
            get
            {
                return ResourceManager.GetString("Api_Get_Rol_Response", resourceCulture);
            }
        }
        public static string Api_User_GetLogin_Invalid
        {
            get
            {
                return ResourceManager.GetString("Api_User_GetLogin_Invalid", resourceCulture);
            }
        }
        public static string Api_User_GetEmail_Invalid
        {
            get
            {
                return ResourceManager.GetString("Api_User_GetEmail_Invalid", resourceCulture);
            }
        }
        public static string Api_Successful
        {
            get
            {
                return ResourceManager.GetString("Api_Successful", resourceCulture);
            }
        }
        public static string Api_Get_RecoveryPassword_Created_Response
        {
            get
            {
                return ResourceManager.GetString("Api_Get_RecoveryPassword_Created_Response", resourceCulture);
            }
        }

        public static string Api_DocumentType_GetById_NotFound
        {
            get
            {
                return ResourceManager.GetString("Api_DocumentType_GetById_NotFound", resourceCulture);
            }
        }
        public static string Api_Get_User_Duplicated_Response
        {
            get
            {
                return ResourceManager.GetString("Api_Get_User_Duplicated_Response", resourceCulture);
            }
        }
        public static string Api_Servererror
        {
            get
            {
                return ResourceManager.GetString("Api_Servererror", resourceCulture);
            }
        }
        public static string Api_Get_Rol_Created_Response
        {
            get
            {
                return ResourceManager.GetString("Api_Get_Rol_Created_Response", resourceCulture);
            }
        }
        public static string Api_Get_User_Created_Response
        {
            get
            {
                return ResourceManager.GetString("Api_Get_User_Created_Response", resourceCulture);
            }
        }
        public static string Api_Get_Rol_Duplicated_Response
        {
            get
            {
                return ResourceManager.GetString("Api_Get_Rol_Duplicated_Response", resourceCulture);
            }
        }
        public static string Api_Rol_GetById_Error
        {
            get
            {
                return ResourceManager.GetString("Api_Rol_GetById_Error", resourceCulture);
            }
        }
        public static string Api_Rol_GetById_NotFound
        {
            get
            {
                return ResourceManager.GetString("Api_Rol_GetById_NotFound", resourceCulture);
            }
        }
        public static string Api_Rol_GetByName_Error
        {
            get
            {
                return ResourceManager.GetString("Api_Rol_GetByName_Error", resourceCulture);
            }
        }
        public static string Api_Rol_Select_Error
        {
            get
            {
                return ResourceManager.GetString("Api_Rol_Select_Error", resourceCulture);
            }
        }
        public static string Api_Badrequest
        {
            get
            {
                return ResourceManager.GetString("Api_Badrequest", resourceCulture);
            }
        }

    }
}
